### ISSUE TITLE
systemd-networkd bridge wiki changes

### ISSUE THREAD

**Issue by ImNtReal** [Jamesits/systemd-named-netns#10]
On my system, I also needed a .netdev file for the bridge
```
[NetDev]
Name=br0
Kind=bridge
```
And I had to use restart instead of reload, to get systemd-networkd to pickup the new config, as reload wasn't an option.

**Comment by Jamesits** [comment]
There are some typos on the wiki, now should be fixed. Also `reload` is now replaced with `restart`. Much thanks.
