### ISSUE TITLE
Tag version/releases to make packaging easier

### ISSUE THREAD

**Issue by aragilar** [Jamesits/systemd-named-netns#19]
Currently there are no tags/releases, I was looking at adding this to Debian/Ubuntu, but the absence of any tagging makes this much harder. Could some scheme be agreed to about when something is tagged, and with what version?

**Comment by Jamesits** [comment]
I'm not exactly sure how to tag this since this is basically a bunch of scripts/configs. Do you have any advice on what scheme to use (e.g. `major.minor` or `major.minor.revision` or anything else)?

**Comment by aragilar** [comment]
`major.minor` is probably more than sufficient (I've also seen `major.releasedate`, if that seems nicer?)

**Comment by Jamesits** [comment]
I think `major.releasedate` should work fine here. I've tagged https://github.com/Jamesits/systemd-named-netns/releases/tag/v1.20190822 now.
