### ISSUE TITLE
netnsinit device name suffix

### ISSUE THREAD

**Issue by p00h** [Jamesits/systemd-named-netns#23]
https://github.com/Jamesits/systemd-named-netns/blob/410f22af75808812fd8653d43c2a04fc19b44be5/scripts/netnsinit#L138
Below commands that uses `DEVNAME_INSIDE_TMP_SUFFIX` variable fails if resulting calculated interface name consists of more than 16 symbols:
https://github.com/Jamesits/systemd-named-netns/blob/410f22af75808812fd8653d43c2a04fc19b44be5/scripts/netnsinit#L141-L142

**Comment by Jamesits** [comment]
Yes, I know that Linux doesn't support long interface names. This is now documented.

(Mistakenly referenced #22 in my commit messages, sorry)
