### ISSUE TITLE
systemctl stop  netns@a should kill all processes in netns 'a'

### ISSUE THREAD

**Issue by ezbik** [Jamesits/systemd-named-netns#26]
%Subj.

```
systemctl start  netns@a
chnetns  a sleep 22222222 &
systemctl stop netns@a
```

The process **sleep** remains.

Solution:

```
PIDS=$(ip netns pids %I) ; echo $PIDS
ip netns del %I
kill $PIDS 
```

**Comment by Jamesits** [comment]
Hmmm I personally think it is ok to do a delayed deletion, just like we do to the files, after you remove it, it will only be actually released after the last process locking it quits. As this project is intended to be used under systemd, you can use systemd's native  dependency management to kill all the processes before removing the netns. 

Is there any use cases I haven't thought of where you really need to kill the processes inside the netns by hand?
