### ISSUE TITLE
Change NIC prefix

### ISSUE THREAD

**Issue by st31ny** [Jamesits/systemd-named-netns#8]
In my master branch https://github.com/steinymity/systemd-named-netns I changed the NIC prefix from `ve-` to `vn-` because `ve-` is already used by `systemd-nspawn` (i.e., to avoid collisions). Particularily, there is a default .network file (on my system in `/lib/systemd/network/80-container-ve.network`) that matches on all ve-* interfaces and automatically assigns IPs (if systemd-networkd is active).

Before pushing this backwards-incompatible change I wanted to ask about your opinions on this. Ideally, the prefix would be configurable, however, systemd doesn't allow to use variables in lines other than Exec*.

**Comment by Jamesits** [comment]
I use ve- because it is a veth type interface. `systemd-nspawn` seems to be using the same name for the same reason… 

If a default config of `systemd-networkd` is going to break this, then it is ok to change the prefix. The project is in an early stage so don’t be afraid to make breaking changes.
