### ISSUE TITLE
Simplify configuration files

### ISSUE THREAD

**Issue by st31ny** [Jamesits/systemd-named-netns#9]
In my master branch https://github.com/steinymity/systemd-named-netns I refactored the common parts of netns-nat@.service and netns-bridge@.service and created another service netns-tunnel@.service that just creates a pair of connected interfaces.
To facilitate this refactoring, however, I had to remove the type-dependent config files. I.e., there are only `/etc/default/netns` and `/etc/default/netns-%I`. As netns-nat and netns-bridge conflict each other anyway, I don't think this is a major drawback.
However, this is of course backward-incompatible, so what do you think about merging the config files?

**Comment by Jamesits** [comment]
I think it is acceptable. Let’s move fast and broke things! ;)

**Comment by st31ny** [comment]
Awesome :D
